site_name: 'Architecture Scoring Docs'
docs_dir: docs
nav:
  - Главное описание: plan.md
  - Quality Requirements:
      - Критерии качества: requirements/quality-requirements.md
  - AI Usage: ai-usage.md
  - Sprints:
      - Sprint 0:
          - Initial Research: sprints/sprint-0/initial-research.md
          - Meeting: sprints/sprint-0/meeting.md
          - Report: sprints/sprint-0/report.md
      - Sprint 1:
          - Script Intervieww: sprints/sprint-1/script-interview.md
          - Team Meeting 1: sprints/sprint-1/team-meeting-1.md
